# Use the official Node.js 18 base image
FROM node:20

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install
# Copy the rest of the application code
COPY . .
RUN npm gcp-build

# Expose the port on which your Express.js application runs
EXPOSE 3000

# Start the application
CMD ["npm", "start"]